# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Build the Docker image
#       # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
#       run: |
#           chmod -R a+w ./
#           docker compose -f docker-compose.yml build

name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and Push the Docker image
        run: |
          docker build . --file Dockerfile --tag menleo-server:latest
          docker push sebastianrdz01/menleo-server:latest
